INCLUDE_GUARD(GLOBAL)

FIND_PACKAGE(Git REQUIRED QUIET)

EXECUTE_PROCESS(
    COMMAND git rev-parse HEAD
    OUTPUT_VARIABLE WEBCLTRANSLATOR_GIT_SHA_LONG
    WORKING_DIRECTORY ${WEBCLTRANSLATOR_ROOT}
    OUTPUT_STRIP_TRAILING_WHITESPACE)

STRING(SUBSTRING ${WEBCLTRANSLATOR_GIT_SHA_LONG} 0 8 WEBCLTRANSLATOR_GIT_SHA)

EXECUTE_PROCESS(
    COMMAND git rev-parse --abbrev-ref HEAD
    OUTPUT_VARIABLE WEBCLTRANSLATOR_BRANCH_NAME
    WORKING_DIRECTORY ${WEBCLTRANSLATOR_ROOT}
    OUTPUT_STRIP_TRAILING_WHITESPACE)

EXECUTE_PROCESS(
    COMMAND git rev-list --count HEAD
    OUTPUT_VARIABLE WEBCLTRANSLATOR_INCR
    WORKING_DIRECTORY ${WEBCLTRANSLATOR_ROOT}
    OUTPUT_STRIP_TRAILING_WHITESPACE)

WEBCLTRANSLATOR_NUMBER_TO_HEX(NUMBER ${WEBCLTRANSLATOR_INCR} OUTPUT_VARIABLE
                              WEBCLTRANSLATOR_HEX)
SET(WEBCLTRANSLATOR_HEX "0x${WEBCLTRANSLATOR_HEX}")
STRING(TIMESTAMP WEBCLTRANSLATOR_TIME "%Y%m%d")

MESSAGE(STATUS "WebCLTranslator Version:")
WEBCLTRANSLATOR_DICT(SET WEBCLTRANSLATOR_VERSION sha
                     ${WEBCLTRANSLATOR_GIT_SHA_LONG})
WEBCLTRANSLATOR_DICT(SET WEBCLTRANSLATOR_VERSION sha8
                     ${WEBCLTRANSLATOR_GIT_SHA})
WEBCLTRANSLATOR_DICT(SET WEBCLTRANSLATOR_VERSION branch
                     ${WEBCLTRANSLATOR_BRANCH_NAME})
WEBCLTRANSLATOR_DICT(SET WEBCLTRANSLATOR_VERSION incr ${WEBCLTRANSLATOR_INCR})
WEBCLTRANSLATOR_DICT(SET WEBCLTRANSLATOR_VERSION hex ${WEBCLTRANSLATOR_HEX})
WEBCLTRANSLATOR_DICT(SET WEBCLTRANSLATOR_VERSION time ${WEBCLTRANSLATOR_TIME})
WEBCLTRANSLATOR_DICT(
    SET WEBCLTRANSLATOR_VERSION version
    ${WEBCLTRANSLATOR_INCR}.${WEBCLTRANSLATOR_TIME}.${WEBCLTRANSLATOR_GIT_SHA})
WEBCLTRANSLATOR_DICT(PRETTY_PRINT WEBCLTRANSLATOR_VERSION)

UNSET(WEBCLTRANSLATOR_GIT_SHA_LONG)
UNSET(WEBCLTRANSLATOR_GIT_SHA)
UNSET(WEBCLTRANSLATOR_BRANCH_NAME)
UNSET(WEBCLTRANSLATOR_INCR)
UNSET(WEBCLTRANSLATOR_HEX)
UNSET(WEBCLTRANSLATOR_TIME)
